[Distribution]
Distribution=arch

[Build]
Incremental=yes
CacheDirectory=mkosi.cache

[Content]
KernelCommandLine=
        root=dissect
        mount.usr=dissect

        rw
        audit=0
        systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:root=encrypted+absent:swap=encrypted+unused+absent:home=unprotected+absent:=ignore
        systemd.image_filter=usr=elvOS_*:usr-verity=elvOS_*:usr-verity-sig=elvOS_*:root=elvOS-*:swap=elvOS-*:home=elvOS-*
        ipe.enforce=0

[Runtime]
RuntimeSize=64G
RAM=4G
CPUs=4
VirtualMachineMonitor=qemu
Console=gui
Ephemeral=yes

[Output]
OutputDirectory=mkosi.output
