#!/usr/bin/nft -f

flush ruleset

table inet filter {
        chain input {
                type filter hook input priority filter; policy drop;

                ct state established,related accept
                ct state invalid drop
                iif lo accept

                ip6 nexthdr icmpv6 icmpv6 type {
                        destination-unreachable,
                        packet-too-big,
                        time-exceeded,
                        parameter-problem,
                        echo-request,
                        echo-reply,
                        nd-router-solicit,
                        nd-router-advert,
                        nd-neighbor-solicit,
                        nd-neighbor-advert,
                        mld-listener-query,
                        mld-listener-report,
                        mld-listener-done,
                        mld2-listener-report
                } accept

                ip protocol icmp icmp type {
                        destination-unreachable,
                        time-exceeded,
                        parameter-problem,
                        echo-request,
                        echo-reply
                } accept

                ip6 daddr fe80::/64 udp dport 546 accept

                udp dport 5353 accept

                counter comment "dropped inbound"
        }

        chain forward {
                type filter hook forward priority filter; policy drop;
                counter comment "dropped forward"
        }

        chain output {
                type filter hook output priority filter; policy accept;
        }
}

include "/etc/nftables.d/*.conf"
