[Output]
SplitArtifacts=uki,partitions
ManifestFormat=json

Format=disk
ImageId=elvOS
Output=%i_%v_%a

[Validation]
SecureBoot=yes
SignExpectedPcr=yes

[Content]
Locale=en_US.UTF-8
LocaleMessages=en_US.UTF-8
Keymap=fr-pc
Timezone=Europe/Paris
Hostname=elvos-????-????

UnifiedKernelImageFormat=%i_%v_%a

InitrdProfiles=
KernelInitrdModules=default

Bootable=yes
Bootloader=systemd-boot

Packages=
        # Core system
        base
        diffutils
        base-devel
        linux
        linux-firmware
        systemd
        amd-ucode
        dbus-broker
        dbus-broker-units
        polkit
        sbctl
        reflector
        dpkg
        bash
        coreutils
        curl

        # Filesystems
        btrfs-progs
        dosfstools
        erofs-utils

        # Disk encryption and measured boot
        cryptsetup
        tpm2-tss
        tpm2-tools
        libfido2

        # TLS trust and signing
        ca-certificates
        p11-kit
        openssl
        sbsigntools

        # Network
        iwd
        nftables
        wireguard-tools
        iputils
        openssh
        wireless-regdb

        # Firmware updates
        fwupd

        # Console
        kbd
        less
        nano
        which
        tree

        systemd-ukify

RemoveFiles=
        /boot/*-ucode.img

VolatilePackages=
        systemd-ukify
