[Output]
SplitArtifacts=uki,partitions
ManifestFormat=json

Format=disk
ImageId=elvOS
Output=%i_%v_%a

[Validation]
SecureBoot=yes
SignExpectedPcr=yes

[Content]
Locale=en_US.UTF-8
LocaleMessages=en_US.UTF-8
Keymap=fr
Timezone=Europe/Paris
Hostname=elvos-????-????

UnifiedKernelImageFormat=%i_%v_%a

InitrdProfiles=
KernelInitrdModules=default

Bootable=yes
Bootloader=systemd-boot

Packages=
        # Core system
        base
        linux
        linux-firmware
        amd-ucode
        dbus-broker
        dbus-broker-units
        polkit
        sbctl
        reflector
        dpkg

        # Filesystems
        btrfs-progs
        dosfstools
        erofs-utils

        # Disk encryption and measured boot
        cryptsetup
        tpm2-tss
        tpm2-tools
        libfido2

        # TLS trust and signing
        ca-certificates
        p11-kit
        openssl
        sbsigntools

        # Network
        iwd
        nftables
        iputils
        openssh
        wireless-regdb

        # Firmware updates.
        fwupd

        # Console
        kbd
        less
        nano
        which

        # Building further images with mkosi on this machine
        archlinux-keyring
        bash
        btrfs-progs
        ca-certificates
        coreutils
        cpio
        curl
        dosfstools
        e2fsprogs
        erofs-utils
        grub
        keyutils
        kmod
        libseccomp
        mtools
        opensc
        openssl
        p11-kit
        pacman
        pkcs11-provider
        python
        sbsigntools
        squashfs-tools
        systemd
        systemd-ukify
        tar
        xfsprogs
        xz
        zstd
        qemu-full
        mkosi

        systemd-ukify

RemoveFiles=
        /boot/*-ucode.img

VolatilePackages=
        systemd-ukify
