[Content]

Packages=
        # Graphics
        mesa
        vulkan-radeon
        vulkan-virtio
        brightnessctl

        # Sound
        pipewire
        pipewire-pulse
        pipewire-alsa
        wireplumber
        sof-firmware

        # Fonts
        noto-fonts-emoji
        ttf-lilex-nerd
        ttf-ibm-plex

        desktop-file-utils
        power-profiles-daemon
        ibus

        # Login Manager
        gdm

        # Gnome
        gnome-backgrounds
        gnome-control-center
        gnome-keyring
        gnome-menus
        gnome-session
        gnome-settings-daemon
        gnome-shell
        gnome-disk-utility
        gnome-system-monitor
        gnome-terminal
        gnome-text-editor

        # Desktop Env
        niri
        quickshell
        greetd

        # Portals
        xdg-desktop-portal
        xdg-desktop-portal-gnome
        xdg-desktop-portal-gtk
        xdg-user-dirs-gtk
        xdg-utils

        # Social
        element-desktop
        discord

        # Misc
        nautilus
        udiskie
        xwayland-satellite
        noctalia
        alacritty
        firefox
        chezmoi
        keyd
        libreoffice-fresh
