[Content]

Packages=
        # Graphics
        mesa
        vulkan-radeon

        # Sound
        pipewire
        pipewire-pulse
        pipewire-alsa
        wireplumber
        sof-firmware

        # Fonts
        noto-fonts
        adobe-source-code-pro-fonts

        desktop-file-utils
        power-profiles-daemon
        ibus

        # Login Manager
        gdm

        # Gnome
        gnome-backgrounds
        gnome-control-center
        gnome-keyring
        gnome-menus
        gnome-session
        gnome-settings-daemon
        gnome-shell
        gnome-system-monitor
        gnome-terminal
        gnome-text-editor

        # Niri
        niri

        # Portals
        xdg-desktop-portal
        xdg-desktop-portal-gnome
        xdg-desktop-portal-gtk
        xdg-user-dirs-gtk

        # Misc
        nautilus
        xwayland-satellite
        fuzzel
        mako
        alacritty
        nushell
        zed
        jujutsu
        firefox
