[Content]

Packages=
        # Graphics
        mesa
        vulkan-radeon
        vulkan-virtio
        brightnessctl

        # Sound
        pipewire
        pipewire-pulse
        pipewire-alsa
        wireplumber
        sof-firmware

        # Fonts
        noto-fonts-emoji
        ttf-lilex-nerd
        ttf-ibm-plex

        desktop-file-utils
        power-profiles-daemon
        ibus

        # Gnome
        gnome-keyring
        gnome-disk-utility
        gnome-system-monitor

        # Desktop Env
        niri
        quickshell
        greetd
        fuzzel
        mako
        wl-mirror

        # Portals
        xdg-desktop-portal
        xdg-desktop-portal-gnome
        xdg-desktop-portal-gtk
        xdg-user-dirs-gtk
        xdg-utils

        # Social
        element-desktop
        discord

        # Misc
        nautilus
        udiskie
        xwayland-satellite
        alacritty
        firefox
        chezmoi
        keyd
        libreoffice-fresh
