[Content]

Packages=
        rust
        rust-analyzer
        rust-src
        rust-musl
        rust-aarch64-gnu
        rust-aarch64-musl
        zig
        cargo-zigbuild
        gcc
        musl
        valgrind
        gdb
        glibc
        typst
        python
        uv
        ty
        ruff
        nushell
        zed
        jujutsu
        git
