[theme]
mode = "light"
source         = "custom"
custom_palette = "elvos"

[wallpaper]
enabled = true
transition_on_startup = true

[wallpaper.default]
path = "/usr/share/elvos/wallpaper.jpg"

[bar.default]
position = "top"

[idle.behavior.custom]
timeout = 180
action = "command"
command = "noctalia msg session lock && notify-send 'Session locked'"

[hooks]
started = "noctalia msg panel-toggle launcher"

[nightlight]
enabled              = false
force                = false

temperature_day   = 6500
temperature_night = 4000

[shell]
niri_overview_type_to_launch_enabled = true
